version: '3'

services:
  app:
    build: ./docker/php
    container_name: phpstan-test
    hostname: app.phpstan-test
    volumes:
      - "./:/app:rw"
      - ./docker/php/bashrc.dist:/var/www/.bashrc:ro
      - "./docker/php/cli/php.ini:/etc/php/8.0/cli/php.ini:ro"
      - "./docker/php/fpm/php.ini:/etc/php/8.0/fpm/php.ini:ro"
    env_file:
      - docker-env
    extra_hosts:
      - "host.docker.internal:host-gateway"


